### ISSUE TITLE
Usage in GitLab

### ISSUE THREAD

**Issue by dieterc** [IQSS/dataverse-uploader#14]
Dear,
Can this uploader also been used inside GitLab?
Kind regards

**Comment by atrisovic** [comment]
Hi there!
I think yes with some minor changes. 
The communication with Dataverse is happening here: https://github.com/IQSS/dataverse-uploader/blob/master/dataverse.py and this script can be slightly modified to run from GitLab.

**Comment by PennyHow** [comment]
We have just been experimenting with this and have a script that works with the [Gitlab CI/CD](https://docs.gitlab.com/ee/ci/quick_start/).

```
# Gitlab-to-Dataverse uploader 
dataverse
image: python:3.9

workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == "push"
        
dataverse_uploader:
  variables:
    DATAVERSE_TOKEN: "$DATAVERSE_API_TOKEN"
    DATAVERSE_SERVER: "https://example.dataverse.org"
    DATAVERSE_DATASET_DOI: "doi:10.12345/EXAMPLE"
    GITHUB_DIR: "./"
    DELETE: "false"
    PUBLISH: "false"

  script:
    - apt-get update && apt-get install -y git python3-pip
    - git clone https://github.com/IQSS/dataverse-uploader.git dataverse-uploader
    - cd dataverse-uploader
    - pip install -r requirements.txt
    - echo "$DATAVERSE_TOKEN" "$DATAVERSE_SERVER" "doi:$DATAVERSE_DATASET_DOI" "$CI_PROJECT_URL" "$DELETE" "$PUBLISH"
    - python dataverse.py "$DATAVERSE_TOKEN" "$DATAVERSE_SERVER" "doi:$DATAVERSE_DATASET_DOI" "$CI_PROJECT_URL" -r "$DELETE" -p "$PUBLISH"
```

The `$DATAVERSE_API_TOKEN` is the API key, which can be set in the repo's CI/CD variables. The scheduling of this pipeline can either be set in the repo's schedules options, or with the `workflow` `rules` flag

I don't know if this should be an example made readily available in something similar to the [repo readme ](https://github.com/IQSS/dataverse-uploader/blob/master/README.md) or a Gitlab equivalent of [this place](https://github.com/marketplace/actions/dataverse-uploader-action)? Might be useful!
